# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeveloperToolManagerExample' do

    pod 'DeveloperToolManager', :path => '../'
    pod 'SbiDevelopMenu', :path => '../Libs/SbiDevelopMenu'
    pod 'SbiUIKit', :path => '../Libs/SbiUIKit'
    pod 'SbiLogger', :path => '../Libs/SbiLogger'
end
